<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>SWIM NLNG</title>
</head>
<body>

<h1>Natural Language Narrative Generator (NLNG)</h1>
<p>
	This web service provides a well-formed JSON for the Sustainable Water through Integrated Modeling (<a href="http://purl.org/swim">SWIM</a>) that contains a data narrative for outputs generated by SWIM's model
</p>
<h2>
	Repository
</h2>
<p>
	Project repository can be found at 
	<a href="https://github.com/iLink-CyberShARE/SWIM-NLNG" target="_blank">
		GitHub
	</a>
</p>
<h2>
	Try the NLNG !
</h2>
<p>
	Request a JSON narrative for the Urban Price output for the 
	<a href="https://water.cybershare.utep.edu/swim/create?usid=5cf40b7" target="_blank">
		scenario "5cf40b7"
	</a>
	<br>
	<br>
</p>
	<br>

<p style="text-align:center; font-size:30px">
	<a href="https://services.cybershare.utep.edu/water/nlng/?
		usid=5cf40b7&varName=urb_price&userType=all&focusArea=urban&
		region=El%20Paso&lang=en&varValueName=miuse&varValueRegion=EPMI_u_f">
		Try me!
	</a>
</p>
</body>
</html>